### ISSUE TITLE
Not possible to create a program with files located on RED brick

### ISSUE THREAD

**Issue by Nic2012** [Tinkerforge/brickv#14]
In some cases y create a new program (e.g. node.js app) on the RED brick and adding files that are only located on the RED is not possible. Only from the desktop pc hosting the brickV.

As an alternative it would be fine to add an "empty" program, and copy certain files to BIN folder on Linux afterwards, but thats also not allowed in case y have a e.g. node.js app.

**Comment by photron** [comment]
The RED Brick is meant as a black box that runs your programs. The official way to get programs onto the RED Brick is using Brick Viewer to upload files from your PC. As there is no official way to get files elsewhere on the RED Brick there is no need to be able to create programs from arbitrary files on the RED Brick.

You can create a empty Node.js program. Just add no files in the wizard but already enter the name of the Node.js script file that you want to add later. The select "Never" for the scheduler and create the program. Finally add the files to the bin directory by other means and reconfigure the scheduler or manually start the program.

**Comment by Nic2012** [comment]
> Just add no files in the wizard but already enter the name of the Node.js script file that you want to add later.

I didnt notice that is possible to enter an arbitrary filename in this dropbox, label beside that was red and next button was always disabled as long as y havent selected any existing script:
http://www.tinkerforge.com/de/doc/_images/red_brick_wizard_step3_javascript.jpg
But y mentioned workaround is fine for me.
