### ISSUE TITLE
invalid setting for parameter "hue" of bricklet-rgb is possible

### ISSUE THREAD

**Issue by duaw** [Tinkerforge/brickv#16]
cosmetical issue: 

parameter H (hue) is supposed to take integer values between 0 and 359 (representing angles of a circle)

however, the H-slider allows -1 as minimum value

using os high sierra 10.3.2, brickv 2.3.12, latest firmwares, probably latest brickd, too
(remark: why do you allow  in brickv setting the LED using HSL color space, but not in the API?)

**Comment by photron** [comment]
A hue of -1 means that the hue is undefined, as it is for any gray color with red=green=blue. Brick Viewer uses the Qt QColor class for RGB/HSL conversion and QColor converts RGB gray to an HSL value with a hue of -1 (undefined).

The HSL sliders in Brick Viewer are basically just there for the hue slider, to give the user an easy way to scroll through all the possible colors in a rainbow-like fashion.

**Comment by rtrbt** [comment]
I've reworked the color handling in c749fc3. The slider minimum is fixed in f03557d. The fixes are available in version 2.4.0.
