### ISSUE TITLE
Brick Logger 2.0.5 - CRITICAL - Device "DXt" has unknwon name: Outdoor Weather Bricklet

### ISSUE THREAD

**Issue by capacious** [Tinkerforge/brickv#17]
When downloading the standalone brick logger 2.0.5 and running it on a Red Brick and using a configuration generated by the Brick Viewer > Data Logger I get the following error:
CRITICAL - Device "DXt" has unknwon name: Outdoor Weather Bricklet

The whole part of the Red Brick log is:
2018-03-05T11:11:53.316978+0100
-------------------------------------------------------------------------------
2018-03-05 11:12:04,284 -     INFO - Loading config from file: config.json
2018-03-05 11:12:04,304 -     INFO - Validating config file
2018-03-05 11:12:04,312 - CRITICAL - Device "DXt" has unknwon name: Outdoor Weather Bricklet
2018-03-05 11:12:04,318 - CRITICAL - Validation found 1 errors

So it doesn't pass validation and thus doesn't run stand alone on the Red Brick to monitor and store the values of the Outdoor Sensor (Temp and Humidity).
[config.json.zip](https://github.com/Tinkerforge/brickv/files/1797296/config.json.zip)

Attached the config file as I use it currently and two pictures of the setup and hardware.

![img_2153](https://user-images.githubusercontent.com/7422394/37213868-95302c84-23b3-11e8-8177-d56ea827a7cd.jpg)
![img_2161](https://user-images.githubusercontent.com/7422394/37213869-954bbf26-23b3-11e8-92c6-7b95004f9b3a.jpg)

**Comment by photron** [comment]
Yep, there's a bug. Please test the fixed Brick Logger version 2.0.6 that I've release a few minutes ago.

**Comment by capacious** [comment]
Seems to run ok now! :-) Thanks for fixing so quickly. Small question: where can I find the csv file with the logging of the values? :-)

**Comment by photron** [comment]
The data is written to data.csv in the same directory as the config.json file on the RED Brick. You can download it in the Files section of your program on the RED Brick tab in Brick Viewer.

**Comment by capacious** [comment]
Ah thanks! 😊

For the rest the case can now be closed as all is working perfectly on my Red Brick.

Kind regards,
Daniel
