### ISSUE TITLE
No module named sip when building

### ISSUE THREAD

**Issue by jose1711** [Tinkerforge/brickv#20]
This is from an attempt to build `brickv` on Arch Linux:
```
$ python2 build_pkg.py
building brickv Debian package
removing old build directories
calling build_all_ui.py release
building ..brickv/src/brickv-2.3.16/src/brickv
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/PyQt4/uic/pyuic.py", line 26, in <module>
    from PyQt4 import QtCore
ImportError: No module named sip
```
Can you please advise?
```
$ pacman -Q pyqt4-common python2-pyqt4 
pyqt4-common 4.12.3-1
python2-pyqt4 4.12.3-1
```

**Comment by rtrbt** [comment]
The sip module is missing. It is available in extra: 
```
$ pacman -Ss python2-sip
extra/python2-sip 4.19.13-1 [installed]
    Python 2.x SIP bindings for C and C++ libraries
```

The python2-pyqt4 package should normally depend on it.

**Comment by jose1711** [comment]
`python2-sip` is already installed:
```
$ pacman -Q python2-sip
python2-sip 4.19.13-1
```

**Comment by rtrbt** [comment]
Okay, I've just upgraded python2-pyqt4 from 4.12.1 to 4.12.3 on my machine and could reproduce the bug. Installing python2-sip-pyqt4 from the AUR fixed it for me.

**Comment by jose1711** [comment]
thank you, building `python2-sip-pyqt4` from https://gitlab.com/inemum/inemum_archlinux/raw/master/python2-sip-pyqt4/PKGBUILD solved the issue for me
