### ISSUE TITLE
ModuleNotFoundError: No module named 'brickv.ui_errorreporter'

### ISSUE THREAD

**Issue by jedie** [Tinkerforge/brickv#28]
Calling the `brickv/main.py` results in error:
```
+ cd .venv/brickv/src
+ python brickv/main.py
Traceback (most recent call last):
  File ".../.venv/brickv/src/brickv/main.py", line 89, in <module>
    from brickv.ui_errorreporter import Ui_ErrorReporter
ModuleNotFoundError: No module named 'brickv.ui_errorreporter'
```

https://github.com/Tinkerforge/brickv/blob/a61697977163d9a78fbfc5508b16ca3fd0a25983/src/brickv/main.py#L89

**Comment by borg42** [comment]
Did you run build_src.py in src/ first? It will translate the Qt .ui files in .py files.

**Comment by jedie** [comment]
Ah! That's it ;) Thanks.
